// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportUS.Web.Data;

#nullable disable

namespace SupportUS.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("SupportUS.Web.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SupportUS.Web.Models.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContractorReviewId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerReviewId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("ExpectedDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProfileId1")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractorReviewId");

                    b.HasIndex("CustomerReviewId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileId1");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("SupportUS.Web.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SupportUS.Web.Models.Quest", b =>
                {
                    b.HasOne("SupportUS.Web.Models.Review", "ContractorReview")
                        .WithMany()
                        .HasForeignKey("ContractorReviewId");

                    b.HasOne("SupportUS.Web.Models.Review", "CustomerReview")
                        .WithMany()
                        .HasForeignKey("CustomerReviewId");

                    b.HasOne("SupportUS.Web.Models.Profile", null)
                        .WithMany("CreatedTasks")
                        .HasForeignKey("ProfileId");

                    b.HasOne("SupportUS.Web.Models.Profile", null)
                        .WithMany("CurrentTasks")
                        .HasForeignKey("ProfileId1");

                    b.Navigation("ContractorReview");

                    b.Navigation("CustomerReview");
                });

            modelBuilder.Entity("SupportUS.Web.Models.Review", b =>
                {
                    b.HasOne("SupportUS.Web.Models.Profile", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("SupportUS.Web.Models.Profile", b =>
                {
                    b.Navigation("CreatedTasks");

                    b.Navigation("CurrentTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
